// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";

export function AddMessage(chatID: string, role: string, content: string, reasoning: string): $CancellablePromise<database$0.Message> {
    return $Call.ByID(4122709343, chatID, role, content, reasoning);
}

export function CreateChat(title: string): $CancellablePromise<database$0.Chat> {
    return $Call.ByID(3131947295, title);
}

export function DeleteAllChats(): $CancellablePromise<void> {
    return $Call.ByID(2871730344);
}

export function DeleteChat(id: string): $CancellablePromise<void> {
    return $Call.ByID(4203751448, id);
}

export function DeleteMessage(id: string): $CancellablePromise<void> {
    return $Call.ByID(3328249253, id);
}

export function GetChat(id: string): $CancellablePromise<database$0.Chat> {
    return $Call.ByID(3528470173, id);
}

export function ListChats(): $CancellablePromise<database$0.Chat[] | null> {
    return $Call.ByID(2209091008);
}

export function ListMessages(chatID: string): $CancellablePromise<database$0.Message[] | null> {
    return $Call.ByID(3359549501, chatID);
}

export function UpdateChatTitle(id: string, title: string): $CancellablePromise<void> {
    return $Call.ByID(25100080, id, title);
}
