// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as database$0 from "../database/models.js";

export function APIKey(id: string): $CancellablePromise<string> {
    return $Call.ByID(1998969674, id);
}

export function DeleteProvider(id: string): $CancellablePromise<void> {
    return $Call.ByID(311380091, id);
}

export function DeleteProviderAPIKey(id: string): $CancellablePromise<void> {
    return $Call.ByID(1328835776, id);
}

export function HasProviderAPIKey(id: string): $CancellablePromise<boolean> {
    return $Call.ByID(1468476481, id);
}

export function ListProviders(): $CancellablePromise<database$0.Provider[] | null> {
    return $Call.ByID(3434321949);
}

export function SaveProvider(p: database$0.Provider): $CancellablePromise<void> {
    return $Call.ByID(1968870905, p);
}

export function SetProviderAPIKey(id: string, key: string): $CancellablePromise<void> {
    return $Call.ByID(1644609793, id, key);
}
