// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Timestamps are Unix milliseconds since the Unix epoch.
 */
export interface Chat {
    "id": string;
    "title": string;
    "createdAt": number;
    "updatedAt": number;
}

export interface Message {
    "id": string;
    "chatId": string;
    "role": string;
    "content": string;
    "reasoning"?: string;
    "createdAt": number;
}

export interface Provider {
    "id": string;
    "type": string;
    "name": string;
    "baseUrl": string;
    "model": string;
    "hasApiKey": boolean;
}
